name: Build Flux Wrapper

on:
  push:
    paths:
      - docker/wrapper.Dockerfile
      - scripts/entrypoint.sh
  workflow_dispatch:           # manual button if you need it

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { packages: write, contents: read }

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & push wrapper
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/wrapper.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/comfy-flux-wrapper:latest
