jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      # NEW step – create a lowercase repo string
      - name: Derive lowercase repo
        run: echo "LC_REPO=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build placeholder image
        run: |
          docker build -t ghcr.io/${{ env.LC_REPO }}/spec-render:${{ github.sha }} .
          docker push ghcr.io/${{ env.LC_REPO }}/spec-render:${{ github.sha }}
