name: Build & Push Container
on:
  push:
    paths:
      - 'Dockerfile'
      - 'graphs/**'
      - 'specs/**'
      - '.github/workflows/build.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build placeholder image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/spec-render:${{ github.sha }} .
          docker push ghcr.io/${{ github.repository }}/spec-render:${{ github.sha }}
