name: Build Flux Wrapper

on:
  workflow_dispatch:      # run this workflow only when triggered manually

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write          # needed to push to GHCR

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push wrapper
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/wrapper.Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}/comfy-flux-wrapper:latest
