# .github/workflows/build.yml
name: Build & Push Container

on:
  # manual trigger
  workflow_dispatch:
  # re-build when core files change
  push:
    paths:
      - Dockerfile
      - graphs/**
      - specs/**
      - .github/workflows/build.yml

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read          # read the repo
      packages: write         # push to GHCR

    env:
      IMAGE_NAME: spec-render # repo/<IMAGE_NAME>:tag

    steps:
      - uses: actions/checkout@v4

      # derive fully-lowercase repo owner/name → ${{ steps.repo.outputs.repo }}
      - name: Lower-case repo name
        id: repo
        run: echo "repo=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >>"$GITHUB_OUTPUT"

      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # one build, one push, two tags (SHA + latest) — atomic
      - name: Build & push (sha + latest)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.repo.outputs.repo }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ghcr.io/${{ steps.repo.outputs.repo }}/${{ env.IMAGE_NAME }}:latest
