name: nuke-linode-bucket

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "yes = preview only"
        required: false
        default: "no"
      prefix:
        description: "optional prefix to delete (empty = full wipe)"
        required: false
        default: ""

jobs:
  purge:
    runs-on: ubuntu-latest

    env:
      BUCKET: castlesidegamestudio-spec-sheets
      LINODE_S3_ENDPOINT: ${{ secrets.LINODE_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.LINODE_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.LINODE_SECRET_ACCESS_KEY }}
      DRY_RUN: ${{ (github.event.inputs.dry_run == 'yes') && '1' || '0' }}
      PREFIX: ${{ github.event.inputs.prefix }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install boto3
        run: python -m pip install --quiet boto3

      - name: Run bucket wipe
        run: python scripts/linode_nuke_bucket.py
