# .github/workflows/render.yml
# ---------------------------------------------------------------------------
# GitHub Actions workflow that launches a Qwen-3 image-generation batch
# job on RunPod (H100 NVL) and uploads results to Linode object storage.
# ---------------------------------------------------------------------------

name: Launch Render Batch

on:
  workflow_dispatch:
    inputs:
      prompt_glob:
        description: NDJSON files to include in this batch
        default: 'addendums/**/*.ndjson'
      image_name:
        description: Container image tag
        default: 'pytorch/pytorch:2.3.1-cuda11.8-cudnn8-runtime'
      gpu_type:
        description: GPU type for the pod
        default: 'NVIDIA H100 NVL'               # ← exact RunPod enum
      volume_gb:
        description: Disk size in GB (optional)
        default: ''
      model_id:
        description: Qwen-3 model ID
        default: 'Qwen/Qwen3-32B'
      width:
        description: Output image width in pixels
        default: '1920'
      height:
        description: Output image height in pixels
        default: '1080'
      orthographic:
        description: Use orthographic projection?
        type: boolean
        default: true

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          pip install requests \
                      "transformers>=4.51.0" \
                      accelerate \
                      bitsandbytes

      - name: Launch On-Demand Pod
        env:
          # ── RunPod auth ──────────────────────────────────────────────
          RUNPOD_API_KEY:          ${{ secrets.RUNPOD_API_KEY }}

          # ── Linode object-storage creds ──────────────────────────────
          LINODE_ACCESS_KEY_ID:     ${{ secrets.LINODE_ACCESS_KEY_ID }}
          LINODE_SECRET_ACCESS_KEY: ${{ secrets.LINODE_SECRET_ACCESS_KEY }}
          LINODE_DEFAULT_REGION:    ${{ secrets.LINODE_DEFAULT_REGION }}
          LINODE_S3_ENDPOINT:       ${{ secrets.LINODE_S3_ENDPOINT }}

          # ── Batch parameters (forwarded to the pod) ──────────────────
          PROMPT_GLOB:  ${{ inputs.prompt_glob }}
          IMAGE_NAME:   ${{ inputs.image_name }}
          GPU_TYPE:     ${{ inputs.gpu_type }}
          VOLUME_GB:    ${{ inputs.volume_gb }}

          # ── Qwen-3 parameters ────────────────────────────────────────
          MODEL_ID: ${{ inputs.model_id }}
          WIDTH:    ${{ inputs.width }}
          HEIGHT:   ${{ inputs.height }}
          ORTHO:    ${{ inputs.orthographic }}

        run: python scripts/launch_pod_on_demand.py
