name: Launch Render Batch

on:
  workflow_dispatch:
    inputs:
      prompt_glob:
        description: NDJSON files to include in this batch
        default: 'addendums/**/*.ndjson'
      image_tag:
        description: Container tag (SHA or "latest")
        default: 'latest'
      gpu_type:
        description: "For On-Demand. Examples: 'NVIDIA A40', 'NVIDIA GeForce RTX 3090', etc."
        default: 'NVIDIA A40'

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: pip install requests

      - name: Launch On-Demand Pod
        env:
          # Required for spinning up the Pod
          RUNPOD_API_KEY: ${{ secrets.RUNPOD_API_KEY }}

          # If your container itself uploads to S3:
          AWS_ACCESS_KEY_ID:      ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION:     ${{ secrets.AWS_DEFAULT_REGION }}

          PROMPT_GLOB: ${{ inputs.prompt_glob }}
          IMAGE_TAG:   ${{ inputs.image_tag }}
          GPU_TYPE:    ${{ inputs.gpu_type }}
        run: python scripts/launch_pod_on_demand.py
