name: Launch Render Batch

on:
  workflow_dispatch:
    inputs:
      prompt_glob:
        description: NDJSON files to include in this batch
        default: 'addendums/**/*.ndjson'

      image_name:
        description: Container image tag
        default: 'ghcr.io/castlesidegamestudio/comfy-flux-wrapper:latest'

      gpu_type:
        description: GPU type for the pod
        default: 'NVIDIA A40'

      volume_gb:
        description: Disk size in GB (must fit Flux models)
        default: '120'

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install requests

      - name: Launch On-Demand Pod
        env:
          RUNPOD_API_KEY:        ${{ secrets.RUNPOD_API_KEY }}
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION:    ${{ secrets.AWS_DEFAULT_REGION }}

          PROMPT_GLOB: ${{ inputs.prompt_glob }}
          IMAGE_NAME:  ${{ inputs.image_name }}
          GPU_TYPE:    ${{ inputs.gpu_type }}
          VOLUME_GB:   ${{ inputs.volume_gb }}

        run: python scripts/launch_pod_on_demand.py
