name: Launch Render Batch
on:
  workflow_dispatch:
    inputs:
      prompt_glob:
        description: NDJSON glob (default all)
        required: false
        default: 'addendums/**/*.ndjson'
      image_tag:
        description: Spec-render container tag
        required: false
        default: 'latest'
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start RunPod batch
        env:
          RUNPOD_API_KEY: ${{ secrets.RUNPOD_API_KEY }}
          PROMPT_GLOB: ${{ inputs.prompt_glob }}
          IMAGE_TAG:   ${{ inputs.image_tag }}
        run: |
          echo "Pretend we are launching RunPod here"
          # real command would be: python scripts/launch_pod_cli.py "$PROMPT_GLOB" "$IMAGE_TAG"
