name: Launch Render Batch

on:
  workflow_dispatch:
    inputs:
      prompt_glob:
        description: NDJSON files to include in this batch
        default: 'addendums/**/*.ndjson'

      image_name:                     # ← public Docker-Hub tag
        description: Container image tag
        default: 'valyriantech/comfyui-with-flux:latest'

      gpu_type:
        description: "GPU type, e.g. 'NVIDIA A40'"
        default: 'NVIDIA A40'

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install requests

      - name: Launch On-Demand Pod
        env:
          # RunPod auth
          RUNPOD_API_KEY: ${{ secrets.RUNPOD_API_KEY }}

          # S3 creds forwarded to the container
          AWS_ACCESS_KEY_ID:      ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION:     ${{ secrets.AWS_DEFAULT_REGION }}

          # batch-specific settings
          PROMPT_GLOB:  ${{ inputs.prompt_glob }}
          IMAGE_NAME:   ${{ inputs.image_name }}   # ← passed to launcher
          GPU_TYPE:     ${{ inputs.gpu_type }}

        run: python scripts/launch_pod_on_demand.py
