# .github/workflows/render.yml
# ---------------------------------------------------------------------------
# Launch a PixArt-α XL batch on RunPod and archive the PNGs to Linode S3.
# ---------------------------------------------------------------------------

name: Launch Render Batch (PixArt-α)

on:
  workflow_dispatch:
    inputs:
      prompt_glob:
        description: NDJSON prompt files to include
        default: 'addendums/**/*.ndjson'

      seed:
        description: RNG seed (deterministic)
        default: '123456'

      image_name:
        description: Container image tag
        default: 'pytorch/pytorch:2.3.1-cuda11.8-cudnn8-runtime'

      gpu_type:
        description: RunPod GPU type
        default: 'NVIDIA H100 NVL'          # ← back to the trusted GPU

      volume_gb:
        description: Optional pod disk size
        default: ''

      model_id:
        description: Diffusers model ID
        default: 'PixArt-alpha/PixArt-XL-2-1024-MS'

      width:
        description: Sprite-sheet width in px  (3 × panel width)
        default: '3072'                     # 1024 px × 3 panels

      height:
        description: Panel height in px
        default: '1024'

      orthographic:
        description: Use orthographic projection?
        type: boolean
        default: true

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install local helper deps
        run: pip install requests

      - name: Launch On-Demand Pod
        env:
          # RunPod
          RUNPOD_API_KEY:          ${{ secrets.RUNPOD_API_KEY }}

          # Linode S3
          LINODE_ACCESS_KEY_ID:     ${{ secrets.LINODE_ACCESS_KEY_ID }}
          LINODE_SECRET_ACCESS_KEY: ${{ secrets.LINODE_SECRET_ACCESS_KEY }}
          LINODE_DEFAULT_REGION:    ${{ secrets.LINODE_DEFAULT_REGION }}
          LINODE_S3_ENDPOINT:       ${{ secrets.LINODE_S3_ENDPOINT }}

          # Batch parameters
          PROMPT_GLOB:  ${{ inputs.prompt_glob }}
          SEED:         ${{ inputs.seed }}
          IMAGE_NAME:   ${{ inputs.image_name }}
          GPU_TYPE:     ${{ inputs.gpu_type }}
          VOLUME_GB:    ${{ inputs.volume_gb }}

          # PixArt-α parameters
          MODEL_ID:     ${{ inputs.model_id }}
          WIDTH:        ${{ inputs.width }}
          HEIGHT:       ${{ inputs.height }}
          ORTHO:        ${{ inputs.orthographic }}

        run: python scripts/launch_pod_on_demand.py
