name: Launch Render Batch

on:
  workflow_dispatch:
    inputs:
      prompt_glob:
        description: NDJSON files to include in this batch
        default: 'addendums/**/*.ndjson'
      image_name:
        description: Container image tag
        default: 'runpod/pytorch:2.1-cuda11.8-devel-ubuntu22.04'
      gpu_type:
        description: GPU type for the pod
        default: 'NVIDIA A40'
      volume_gb:
        description: Disk size in GB (optional, leave blank for launcher default)
        default: ''
      model_id:
        description: Hugging Face Diffusers model ID (e.g. modelscope/qwen-image-7b)
        default: 'modelscope/qwen-image-7b'
      width:
        description: Output image width in pixels
        default: '1920'
      height:
        description: Output image height in pixels
        default: '1080'
      orthographic:
        description: Use orthographic projection?
        type: boolean
        default: true

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install requests

      - name: Launch On-Demand Pod
        env:
          # RunPod auth
          RUNPOD_API_KEY:        ${{ secrets.RUNPOD_API_KEY }}

          # Linode object-storage creds
          LINODE_ACCESS_KEY_ID:     ${{ secrets.LINODE_ACCESS_KEY_ID }}
          LINODE_SECRET_ACCESS_KEY: ${{ secrets.LINODE_SECRET_ACCESS_KEY }}
          LINODE_DEFAULT_REGION:    ${{ secrets.LINODE_DEFAULT_REGION }}
          LINODE_S3_ENDPOINT:       ${{ secrets.LINODE_S3_ENDPOINT }}

          # Batch settings
          PROMPT_GLOB:  ${{ inputs.prompt_glob }}
          IMAGE_NAME:   ${{ inputs.image_name }}
          GPU_TYPE:     ${{ inputs.gpu_type }}
          VOLUME_GB:    ${{ inputs.volume_gb }}

          # Qwen-3 Diffusers settings
          MODEL_ID:     ${{ inputs.model_id }}
          WIDTH:        ${{ inputs.width }}
          HEIGHT:       ${{ inputs.height }}
          ORTHO:        ${{ inputs.orthographic }}

        run: python scripts/launch_pod_on_demand.py
