name: Launch Render Batch
on:
  workflow_dispatch:
    inputs:
      prompt_glob: { description: NDJSON glob, default: 'addendums/**/*.ndjson' }
      image_tag:   { description: Container tag,  default: 'latest' }
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - env:
          RUNPOD_API_KEY: ${{ secrets.RUNPOD_API_KEY }}
      - run: echo "stub – replace with scripts/launch_pod_cli.py later"
