name: Validate Prompts
on:
  push:
    paths:
      - 'addendums/**/*.ndjson'
      - 'scripts/validate_prompts.py'
      - '.github/workflows/validate.yml'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install deps
        run: pip install jsonschema
      - name: Run prompt validator
        run: python scripts/validate_prompts.py addendums
